Repository Pocket-SOL/FE, pull requests merged in 2024-12, with the labels that each got.

#127 Feature/77 child registration acceptance
  package-lock.json
  package.json
  src/App.jsx
  src/components/HomePage.module.css
  src/contexts/WebSocketContext.jsx
  src/layouts/Layout.jsx
  src/pages/Children/HomePage.jsx
  src/pages/Children/NotificationPage.jsx
  src/pages/Parents/ChildRegistrationPage.jsx
  src/pages/Parents/HomePage.jsx
  src/routers/MainRouter.jsx
Labels: 구현

#130 Feature/129 signup logic
  src/libs/apis/accounts.js
  src/libs/apis/users.js
  src/pages/Start/AuthPage.jsx
  vite.config.js
Labels: 구현

#131 Fix/docker env
  .github/workflows/deploy.yml
  Dockerfile
Labels: 환경설정, 문제해결

#137 Fix : refactor code using try-catch(#136)
  src/pages/Start/AuthPage.jsx
Labels: 문제해결, refactoring

#139 Fix: make VITE_URI(#138)
  src/pages/Start/AuthPage.jsx
Labels: fix, 문제해결

#140 Fix/138 redirect uri
  .github/workflows/deploy.yml
  Dockerfile
  src/pages/Start/AuthPage.jsx
Labels: fix

#149 Fix : connect user with useAuth(#148)
  src/pages/Children/Usage/UsageHistoryPage.jsx
Labels: fix, 문제해결

#150 Fix : connect child with useAuth(#148)
  src/pages/Parents/Usage/UsageHistoryPage.jsx
Labels: fix, 문제해결

#151 Fix : modify proxy route(#148)
  vite.config.js
Labels: fix, 문제해결

#155 Fix : make openbank api in express for using in react
  src/pages/Start/AuthPage.jsx
Labels: fix, 문제해결

#158 Fix : modify fetch User(#116)
  src/libs/apis/users.js
Labels: fix, 문제해결

#161 Fix : modify fetchSchool(#159)
  src/pages/Children/GroupPurchase/School.jsx
Labels: 구현, 문제해결

#166 Feat : get open account info(#162)
  src/libs/apis/accounts.js
  src/pages/Parents/HomePage.jsx
  src/pages/Start/AuthPage.jsx
Labels: 구현

#167 Feat : get open account in children home(#162)
  src/pages/Children/HomePage.jsx
  src/pages/Parents/HomePage.jsx
Labels: 구현

#171 Fix : get account num from db(#162)
  src/pages/Children/HomePage.jsx
  src/pages/Parents/HomePage.jsx
Labels: 구현, 문제해결

#175 Fix/162 fin num db
  src/pages/Children/HomePage.jsx
  src/pages/Parents/HomePage.jsx
Labels: fix

#179 Feature/162 add open db
  src/libs/apis/accounts.js
  src/pages/Children/HomePage.jsx
  src/pages/Parents/HomePage.jsx
Labels: 구현

#186 Fix : modify get child balance according to child presence
  src/pages/Parents/HomePage.jsx
Labels: fix, 문제해결

#189 Fix : add case localeAmount 0
  src/pages/Parents/HomePage.jsx
Labels: 문제해결

#190 Fix/set locale
  src/components/Usage/HistoryItem.jsx
  src/pages/Children/Usage/UsageHistoryPage.jsx
Labels: fix

#192 Fix : modify add navigate to photo upload(#191)
  src/pages/Children/Usage/HistoryDetailPage.jsx
Labels: 문제해결

#193 Fix : remove setchild in dependency array(#191)
  src/pages/Parents/HomePage.jsx
Labels: 문제해결

#194 Fix : modify get child balance in parents' page(#191)
  src/pages/Parents/HomePage.jsx
Labels: 문제해결, refactoring

#209 Fix : test nginx.conf for ssl
  nginx.conf
Labels: 환경설정, fix

#236 Fix : modify load child's balacne in parents using localstorage(#191)
  src/pages/Parents/Usage/UsageHistoryPage.jsx
Labels: 문제해결

#237 Feature/191 fixed history
  src/components/Usage/HistoryItem.jsx
  src/libs/apis/subaccounts.js
  src/pages/Children/Usage/FixedHistoryPage.jsx
  src/pages/Children/Usage/UsageHistoryPage.jsx
  src/routers/MainRouter.jsx
Labels: 구현

#240 Fix : modify allowance amount(#191)
  src/pages/Parents/Allowance/SendAllowancePage.jsx
Labels: 문제해결
