Repository Pocket-SOL/FE, pull requests merged in 2024-11, with the labels that each got.

#4 Feature/3 pages folder setup
  src/pages/Children/Allowance/AllowanceRequestPage.jsx
  src/pages/Children/GroupPurchase/GroupPurchaseListPage.jsx
  src/pages/Children/HomePage.jsx
  src/pages/Children/StudentCardRegistrationPage.jsx
  src/pages/Children/Usage/UsageHistoryPage.jsx
  src/pages/Parents/Allowance/SendAllowancePage.jsx
  src/pages/Parents/HomePage.jsx
  src/pages/Parents/Usage/UsageHistoryPage.jsx
  src/pages/Start/LoginPage.jsx
  src/pages/Start/OnboardingPage.jsx
  src/pages/Start/SignUpPage.jsx
  src/routers/MainRouter.jsx
Labels: 구현

#16 chore : set prettier
  .prettierrc
  package-lock.json
  package.json
Labels: 환경설정

#21 Feature/9 login
  package-lock.json
  package.json
  src/pages/Start/LoginPage.jsx
  vite.config.js
Labels: 구현

#23 Feat : make children usage page(#6)
  src/components/HistoryItem.jsx
  src/components/UsageHistory.module.css
  src/libs/apis/accounts.js
  src/main.jsx
  src/pages/Children/Usage/UsageHistoryPage.jsx
  src/routers/MainRouter.jsx
  vite.config.js
Labels: 구현

#27 Feature/24 parents home
  src/assets/images/assignMission.png
  src/assets/images/bankIcon.png
  src/assets/images/sendAllowance.png
  src/pages/Parents/HomePage.jsx
  src/pages/Parents/HomePage.module.css
  src/routers/MainRouter.jsx
Labels: 구현

#30 feat:SendCompletePage(#29)
  src/assets/images/check.png
  src/pages/Parents/Allowance/SendCompletePage.css
  src/pages/Parents/Allowance/SendCompletePage.jsx
  src/routers/MainRouter.jsx
Labels: 구현

#31 Feature/9 login
  src/App.jsx
  src/context/AuthContext.jsx
  src/pages/Start/LoginPage.jsx
Labels: 구현

#32 Feature/9 login
  src/context/AuthContext.jsx
  src/pages/Start/LoginPage.jsx
Labels: 문제해결

#33 Feature/24 parents home
  src/components/HomePage.module.css
  src/pages/Parents/HomePage.jsx
  src/routers/MainRouter.jsx
Labels: 구현

#41 Feat : make photo upload page(#39)
  src/components/Usage/ActionButton.jsx
  src/components/Usage/HistoryItem.jsx
  src/components/Usage/Photo.module.css
  src/components/Usage/Usage.module.css
  src/pages/Children/Usage/PhotoUploadPage.jsx
  src/pages/Children/Usage/UsageHistoryPage.jsx
  src/pages/Parents/Usage/UsageHistoryPage.jsx
  src/routers/MainRouter.jsx
Labels: 구현

#44 Fix : modify import route in header
  src/components/Header.jsx
Labels: 문제해결

#37 Feature/25 children home
  src/App.jsx
  src/assets/images/allowanceIcon.png
  src/assets/images/missionIcon.png
  src/assets/images/schoolIcon.png
  src/components/HomePage.module.css
  src/contexts/AuthContext.jsx
  src/pages/Children/HomePage.jsx
  src/pages/Parents/HomePage.jsx
  src/pages/Start/LoginPage.jsx
  src/routers/MainRouter.jsx
  vite.config.js
Labels: 구현

#46 Feature/18 modiheader page
  src/assets/images/mascotImage.png
  src/contexts/AuthContext.jsx
  src/pages/Children/GroupPurchase/Comment.jsx
  src/pages/Children/GroupPurchase/DataSelection.jsx
  src/pages/Children/GroupPurchase/GroupPurchaseDetailPage.jsx
  src/pages/Children/GroupPurchase/GroupPurchaseListPage.jsx
  src/pages/Children/GroupPurchase/GroupPurchaseReg.jsx
  src/pages/Start/Onboarding/IconWithText.jsx
  src/pages/Start/Onboarding/IconWithText.module.css
  src/pages/Start/Onboarding/OnboardingPage.jsx
  src/pages/Start/Onboarding/OnboardingPage.module.css
  src/pages/Start/OnboardingPage.jsx
  src/routers/MainRouter.jsx
  vite.config.js
Labels: 구현

#50 Fix : add exception
  src/pages/Children/Usage/UsageHistoryPage.jsx
Labels: 문제해결

#53 Feat : make Dockerfile(#51)
  Dockerfile
Labels: 환경설정, 구현

#52 Feat : make deploy.yml (#51)
  .github/workflows/deploy.yml
Labels: 환경설정, 구현

#56 Feat : add nginx.conf file
  nginx.conf
Labels: 환경설정, 구현

#58 Fix : modify deploy.yml(#51)
  .github/workflows/deploy.yml
Labels: fix

#65 Feat : add historyDetailPage(#64)
  src/components/Usage/HistoryItem.jsx
  src/libs/apis/histories.js
  src/pages/Children/Usage/HistoryDetailPage.jsx
  src/pages/Children/Usage/UsageHistoryPage.jsx
  src/routers/MainRouter.jsx
Labels: 구현

#69 Feature/7 layout
  index.html
  src/App.jsx
  src/assets/images/titleIcon.png
  src/contexts/AuthContext.jsx
  src/contexts/UserContext.jsx
  src/pages/Children/HomePage.jsx
  src/pages/Parents/HomePage.jsx
  src/pages/Start/LoginPage.jsx
  vite.config.js
Labels: 문제해결, refactoring

#74 Feature/39 loading photo
  src/libs/apis/histories.js
  src/pages/Children/Usage/HistoryDetailPage.jsx
  src/pages/Children/Usage/PhotoUploadPage.jsx
Labels: 구현

#76 Feat : connect page with navigate(#64)
  src/pages/Children/HomePage.jsx
  src/pages/Children/Usage/HistoryDetailPage.jsx
  src/pages/Children/Usage/UsageHistoryPage.jsx
Labels: 구현

#88 Feat : connect page each other with navigate(34)
  src/components/Usage/HistoryItem.jsx
  src/components/Usage/Usage.module.css
  src/pages/Parents/HomePage.jsx
  src/pages/Parents/Usage/UsageHistoryPage.jsx
Labels: 구현

#117 Feat : auth&token with openbank api(#116)
  package-lock.json
  package.json
  src/pages/Start/AuthPage.jsx
  src/pages/Start/LoginPage.jsx
  src/routers/MainRouter.jsx
  vite.config.js
Labels: 구현

#118 Fix : modify school key
  package-lock.json
  package.json
  src/pages/Children/GroupPurchase/School.jsx
Labels: 환경설정, 문제해결

#121 Fix : update token on user model(#116)
  src/pages/Start/AuthPage.jsx
Labels: 구현, 문제해결

#126 Feat : update user seq no (#116)
  src/libs/apis/users.js
  src/pages/Start/AuthPage.jsx
Labels: 구현
